# Generated by Django 3.2.8 on 2021-11-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20211107_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='forget_password_token',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
