# Generated by Django 3.2.8 on 2021-11-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_userinfo_forget_password_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='last_name',
        ),
    ]
