# Generated by Django 3.2.7 on 2021-11-14 20:33

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Name_Ent_Med', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Url', embed_video.fields.EmbedVideoField()),
                ('Type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Learning',
            },
        ),
    ]
