# Generated by Django 3.2.9 on 2021-12-06 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_shippingaddress_shoppingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingAddress',
        ),
    ]
