# Generated by Django 3.2.8 on 2021-11-18 22:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameP', models.CharField(max_length=100)),
                ('descP', ckeditor.fields.RichTextField()),
                ('imageP', models.ImageField(upload_to='./products/images/')),
                ('prixP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materiels',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('typeM', models.CharField(choices=[('Fitness', 'Fitness'), ('BodyBuilding', 'BodyBuilding')], max_length=100)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Proteines',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Vetements',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('genre', models.CharField(choices=[('Femme', 'Femme'), ('Homme', 'Homme')], max_length=100)),
            ],
            bases=('products.product',),
        ),
    ]
